Update optimer script

diff --git a/bin/.local/bin/optimer b/bin/.local/bin/optimer
--- a/bin/.local/bin/optimer
+++ b/bin/.local/bin/optimer
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Version: 1.0.0
+# Version: 2.0.0
 #
 # Description: Resize and compress PNG and JPG/JPEG files
 #
@@ -15,12 +15,12 @@ if [ "$1" == "-h" ]; then
 cat <<EOF
 Optimer: Resize and compress PNG and JPG/JPEG files
 
-Usage: optimer <integer> <filename>
+Usage: optimer <integer> <filename1> <filename2>...
 
-	- integer → the width of the compressed file.
+	- integer → the new width for the compressed file.
 	- filename → a list of files to compress.
 
-Example: optimer 500 picture.png picture.jpeg
+Example: optimer 500 picture.png figure.jpeg image.jpg
 
 Resize is done with convert(1).
 PNG compression is done with optipng(1) and pngcrush(1).
@@ -29,59 +29,45 @@ EOF
 exit 1
 fi
 
-SIZE="$1"
+NEW_WIDTH="$1"
 
-if ! [[ "$SIZE" =~ ^[0-9]+$ ]] ; then
-	echo "Error: first option must be an integer."
-	echo "Usage: optimer <integer> <filename>" >&2; exit 1
+if ! [[ "$NEW_WIDTH" =~ ^[0-9]+$ ]] ; then
+	echo "Error: first option must be an integer: image width in pixels."
+	echo "Usage: optimer <integer> <filename> <filename2>..." >&2; exit 1
 fi
 
-if ! [[ "$SIZE" -gt 0 ]] ; then
-	echo "Error: first option must be greater than 0."
-	echo "Usage: optimer <integer> <filename>" >&2; exit 1
+if ! [[ "$NEW_WIDTH" -gt 0 ]] ; then
+	echo "Error: first option must be an integer greater than 0."
+	echo "Usage: optimer <integer> <filename1> <filename2>..." >&2; exit 1
 fi
-
-img_resize() {
-	convert "$f" -resize "$SIZE" "$RENAME"
-}
-
-img_rename() {
-	RENAME="${NAME}-${WIDTH}.${EXT}"
-	cp "$f" "$RENAME"
-}
-
-opt_png() {
-	echo "Optimizing PNG-image: $RENAME"
-	optipng -o1 --quiet "$RENAME"
-	pngcrush -q "$RENAME" /tmp/$$; mv /tmp/$$ "$RENAME"
-}
-
-opt_jpg() {
-	echo "Optimizing $EXT-image: $RENAME"
-	jpegoptim --max=80 "$RENAME"
-	jpegtran -copy none -optimize -outfile "$RENAME" "$RENAME"
-}
 
 for f in "${@:2}"; do
 	NAME="${f%%.*}"
 	EXT="${f##*.}"
-	WIDTH="$(identify -format '%w' "$f")"
-	RENAME="${NAME}-${SIZE}.${EXT}"
+	INITIAL_WIDTH="$(identify -format '%w' "$f")"
+	RESIZED="${NAME}-.${EXT}"
 
-	if [[ "$WIDTH" -gt "$SIZE" ]] ; then
-		img_resize
+	if [[ "$INITIAL_WIDTH" -gt "$NEW_WIDTH" ]] ; then
+		convert "$f" -resize "$NEW_WIDTH" "$RESIZED"
 	else
-		printf "Image '%s' has a width lower than desired.\n" "$f"
-		printf "Using %s instead of %s.\n\n" "$WIDTH" "$SIZE"
-		img_rename
+		cp "$f" "$RESIZED"
 	fi
 
+	DIMS="$(identify -format '%wx%h' "$RESIZED" 2>/dev/null)"
+	RENAMED="${NAME}-${DIMS}.${EXT}"
+
+	mv "$RESIZED" "$RENAMED"
+
 	if [[ ${EXT,,} == "png" ]] ; then
-		opt_png
+		echo "Optimizing PNG-image: $RENAMED"
+		optipng -o1 --quiet "$RENAMED"
+		pngcrush -q "$RENAMED" /tmp/$$; mv /tmp/$$ "$RENAMED"
 	fi
 
 	if [[ "${EXT,,}" =~ (jpg|jpeg) ]] ; then
-		opt_jpg
+		echo "Optimizing $EXT-image: $RENAMED"
+		jpegoptim --max=80 "$RENAMED"
+		jpegtran -copy none -optimize -outfile "$RENAMED" "$RENAMED"
 	fi
 
 done
